"""
LangGraph State Schema for Revenue Recovery Workflow
"""

from typing import Annotated, Any, Optional, List, Literal
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum
import operator


# ============================================================================
# ENUMS & CONSTANTS
# ============================================================================

class LeakageScenario(str, Enum):
    """Core 5 revenue leakage scenarios"""
    PAYMENT_DEGRADATION = "payment_degradation"
    CHECKOUT_DROPOFF = "checkout_dropoff"
    FAILED_SUBSCRIPTION = "failed_subscription"
    B2B_RECEIVABLES = "b2b_receivables"
    MANDATE_SEQUENCER = "mandate_sequencer"


class RecoveryChannel(str, Enum):
    """Intervention channels"""
    SMART_RETRY = "smart_retry"
    HINGLISH_VOICE = "hinglish_voice"
    WHATSAPP_SMS = "whatsapp_sms"
    DYNAMIC_INCENTIVE = "dynamic_incentive"
    MANDATE_SEQUENCER = "mandate_sequencer"
    B2B_INVOICE_CHASER = "b2b_invoice_chaser"
    HUMAN_ESCALATION = "human_escalation"


class PaymentFailureType(str, Enum):
    """Types of payment failures"""
    DECLINED_CARD = "declined_card"
    INSUFFICIENT_FUNDS = "insufficient_funds"
    GATEWAY_ERROR = "gateway_error"
    AUTHENTICATION_FAILED = "authentication_failed"
    NETWORK_ERROR = "network_error"
    TIMEOUT = "timeout"
    INVALID_CARD = "invalid_card"
    FRAUD_CHECK = "fraud_check"
    SUBSCRIPTION_LAPSED = "subscription_lapsed"
    CHECKOUT_ABANDONED = "checkout_abandoned"
    OVERDUE_INVOICE = "overdue_invoice"
    MANDATE_FAILURE = "mandate_failure"


class RecoveryActionType(str, Enum):
    """Types of recovery actions"""
    RETRY_PAYMENT = "retry_payment"
    UPDATE_PAYMENT_METHOD = "update_payment_method"
    SEND_RECOVERY_EMAIL = "send_recovery_email"
    OFFER_INCENTIVE = "offer_incentive"
    MANUAL_REVIEW = "manual_review"
    CONTACT_CUSTOMER = "contact_customer"
    MANDATE_RETRY = "mandate_retry"
    PAYMENT_PLAN = "payment_plan"
    VOICE_CALL_RECOVERY = "voice_call_recovery"
    WHATSAPP_LINK = "whatsapp_link"
    B2B_CHASER = "b2b_chaser"


class ConfidenceLevel(str, Enum):
    """Confidence levels for diagnosis"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class WorkflowStatus(str, Enum):
    """Status of recovery workflow"""
    PENDING = "pending"
    DIAGNOSING = "diagnosing"
    VERIFIED = "verified"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    REVISING = "revising"
    STOPPED_BY_RULE = "stopped_by_rule"
    ESCALATED = "escalated"


# ============================================================================
# DATA MODELS
# ============================================================================

class PaymentSignal(BaseModel):
    """Signals/indicators about a failed payment or abandoned cart"""
    signal_type: str
    severity: Literal["low", "medium", "high"]
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    details: dict[str, Any] = Field(default_factory=dict)
    source: str = "gateway"


class VoiceDialogueLine(BaseModel):
    """Single turn in simulated Hinglish Voice conversation"""
    speaker: Literal["AI Agent (Aarav)", "Customer", "System"]
    text: str
    timestamp: str
    sentiment: Optional[str] = "neutral"


class VoiceRecoveryData(BaseModel):
    """Data generated by Hinglish Voice Agent"""
    call_id: str
    phone_number: str
    language: str = "Hinglish"
    duration_seconds: int = 42
    sentiment: Literal["positive", "hesitant", "neutral", "frustrated"] = "positive"
    dialogue: List[VoiceDialogueLine] = []
    call_summary: str = ""
    ptp_agreed: bool = False
    ptp_date: Optional[str] = None


class PromiseToPay(BaseModel):
    """Promise to Pay (PTP) tracker item"""
    ptp_id: str
    case_id: str
    customer_id: str
    customer_name: str
    amount: float
    promised_date: str
    status: Literal["pending", "honored", "defaulted", "rescheduled"] = "pending"
    mandate_auto_trigger: bool = True
    channel: str = "voice_call"
    created_at: datetime = Field(default_factory=datetime.utcnow)


class StoppingRuleCheck(BaseModel):
    """Compliance & safety guardrail stopping rule evaluation"""
    rule_name: str
    triggered: bool
    limit_value: str
    current_value: str
    action_taken: str


class DiagnosisResult(BaseModel):
    """Output from the diagnosis node"""
    root_cause: str
    failure_type: PaymentFailureType
    scenario: LeakageScenario = LeakageScenario.PAYMENT_DEGRADATION
    confidence_score: float = Field(ge=0.0, le=1.0)
    reasoning: str
    recovery_likelihood: float = Field(ge=0.0, le=1.0)
    suggested_actions: List[RecoveryActionType]
    channel_recommendation: RecoveryChannel = RecoveryChannel.SMART_RETRY
    internal_notes: str
    stopping_rules: List[StoppingRuleCheck] = []


class RecoveryAction(BaseModel):
    """A bounded recovery action to execute"""
    action_type: RecoveryActionType
    priority: Literal["critical", "high", "medium", "low"]
    channel: RecoveryChannel = RecoveryChannel.SMART_RETRY
    parameters: dict[str, Any] = Field(default_factory=dict)
    retry_count: int = 0
    max_retries: int = 3
    discount_offered: float = 0.0
    discount_cap: float = 15.0  # Max 15% discount bounded rule
    created_at: datetime = Field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None
    result: Optional[dict[str, Any]] = None
    error: Optional[str] = None
    voice_data: Optional[VoiceRecoveryData] = None
    ptp_data: Optional[PromiseToPay] = None


class AuditLogEntry(BaseModel):
    """Audit trail entry for compliance & forensic review"""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    event_type: str
    stage: WorkflowStatus
    action: str
    details: dict[str, Any]
    user_id: Optional[str] = None
    system_decision: bool = True


class CustomerContext(BaseModel):
    """Customer historical context for diagnosis"""
    customer_id: str
    customer_name: str = "Valued Customer"
    customer_email: str = "customer@example.com"
    customer_phone: str = "+91 98765 43210"
    lifetime_value: float = 0.0
    total_transactions: int = 0
    failed_attempts: int = 0
    success_rate: float = 1.0
    average_transaction_amount: float = 0.0
    preferred_payment_method: str = "card"
    preferred_language: str = "Hinglish"
    churn_risk: Literal["low", "medium", "high"] = "low"
    previous_recovery_actions: List[dict[str, Any]] = []


# ============================================================================
# MAIN WORKFLOW STATE
# ============================================================================

class RevenuRecoveryState(BaseModel):
    """Complete state that flows through LangGraph workflow"""
    
    # Identifiers
    payment_id: str
    case_id: str = Field(default_factory=lambda: f"case_{datetime.utcnow().timestamp()}")
    customer_id: str
    
    # Scenario
    scenario: LeakageScenario = LeakageScenario.PAYMENT_DEGRADATION
    
    # Input data
    payment_amount: float
    payment_method: str = "card"
    failure_reason: str = "Payment failed"
    payment_signals: Annotated[List[PaymentSignal], operator.add] = []
    
    # Customer context
    customer_context: Optional[CustomerContext] = None
    
    # Workflow state
    status: WorkflowStatus = WorkflowStatus.PENDING
    current_node: str = ""
    
    # Diagnosis results
    diagnosis: Optional[DiagnosisResult] = None
    
    # Confidence check results
    passes_confidence_check: Optional[bool] = None
    confidence_threshold: float = 0.7  # 70% threshold
    
    # Recovery action
    selected_action: Optional[RecoveryAction] = None
    alternate_actions: Annotated[List[RecoveryAction], operator.add] = []
    
    # Execution results
    execution_result: Optional[dict[str, Any]] = None
    execution_error: Optional[str] = None
    
    # Boundaries & Guardrails
    max_recovery_attempts: int = 3
    recovery_attempts: int = 0
    amount_recovered: float = 0.0
    stopping_rule_hit: Optional[str] = None
    
    # Tracking
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Audit trail
    audit_log: Annotated[List[AuditLogEntry], operator.add] = []
    
    # Revision path
    should_revise: bool = False
    revision_count: int = 0
    max_revisions: int = 2

    class Config:
        use_enum_values = False
        arbitrary_types_allowed = True


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def add_audit_entry(
    state: RevenuRecoveryState,
    event_type: str,
    action: str,
    details: dict[str, Any],
    user_id: Optional[str] = None
) -> RevenuRecoveryState:
    """Add an entry to the audit log"""
    entry = AuditLogEntry(
        event_type=event_type,
        stage=state.status,
        action=action,
        details=details,
        user_id=user_id
    )
    state.audit_log.append(entry)
    state.updated_at = datetime.utcnow()
    return state


def update_status(
    state: RevenuRecoveryState,
    new_status: WorkflowStatus
) -> RevenuRecoveryState:
    """Update workflow status with audit trail"""
    state.status = new_status
    state.updated_at = datetime.utcnow()
    return add_audit_entry(
        state,
        event_type="status_change",
        action=f"Workflow status changed to {new_status.value}",
        details={"previous_status": state.status.value if state.status else None}
    )
